package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.CheckBox;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.Notifier;
import com.google.appinventor.components.runtime.TinyDB;
class login_screen extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Label Label1;
  private Image Image1;
  private Label Label2;
  private HorizontalArrangement HorizontalArrangement2;
  private VerticalArrangement Vertical_Arrangement1;
  private VerticalArrangement VerticalArrangement1;
  private Image Image2;
  private Image Image3;
  private VerticalArrangement VerticalArrangement2;
  private TextBox username_textbox;
  private TextBox password_textbox;
  private VerticalArrangement Vertical_Arrangement2;
  private HorizontalArrangement HorizontalArrangement3;
  private CheckBox EULA_textbox;
  private Label Eula;
  private HorizontalArrangement HorizontalArrangement4;
  private Button Login_button;
  private HorizontalArrangement HorizontalArrangement5;
  private Notifier WrongUserPassNotifier;
  private TinyDB Tiny_DB1;
  protected void $define() {
    this.AppName("Greekathon_team_codeweek");
    this.Title("login_screen");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement1.Height(LENGTH_FILL_PARENT);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Label1 = new Label(HorizontalArrangement1);
    Label1.Height(LENGTH_FILL_PARENT);
    Label1.Width(LENGTH_FILL_PARENT);
    Image1 = new Image(HorizontalArrangement1);
    Image1.Height(LENGTH_FILL_PARENT);
    Image1.Width(LENGTH_FILL_PARENT);
    Image1.Picture("2021-05-07_130219.png");
    Label2 = new Label(HorizontalArrangement1);
    Label2.Height(LENGTH_FILL_PARENT);
    Label2.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement2 = new HorizontalArrangement(this);
    HorizontalArrangement2.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement2.Height(LENGTH_FILL_PARENT);
    HorizontalArrangement2.Width(LENGTH_FILL_PARENT);
    Vertical_Arrangement1 = new VerticalArrangement(HorizontalArrangement2);
    Vertical_Arrangement1.BackgroundColor(0x00FFFFFF);
    Vertical_Arrangement1.Height(LENGTH_FILL_PARENT);
    Vertical_Arrangement1.Width(LENGTH_FILL_PARENT);
    VerticalArrangement1 = new VerticalArrangement(HorizontalArrangement2);
    VerticalArrangement1.AlignHorizontal(2);
    VerticalArrangement1.AlignVertical(2);
    VerticalArrangement1.BackgroundColor(0x00FFFFFF);
    VerticalArrangement1.Height(LENGTH_FILL_PARENT);
    Image2 = new Image(VerticalArrangement1);
    Image2.Picture("account_box_black_24dp.svg");
    Image3 = new Image(VerticalArrangement1);
    Image3.Picture("vpn_key_black_24dp.svg");
    VerticalArrangement2 = new VerticalArrangement(HorizontalArrangement2);
    VerticalArrangement2.AlignVertical(2);
    VerticalArrangement2.BackgroundColor(0x00FFFFFF);
    username_textbox = new TextBox(VerticalArrangement2);
    username_textbox.FontItalic(true);
    username_textbox.Height(LENGTH_FILL_PARENT);
    username_textbox.Width(LENGTH_FILL_PARENT);
    username_textbox.Hint("Hint for Text_Box1");
    password_textbox = new TextBox(VerticalArrangement2);
    password_textbox.Height(LENGTH_FILL_PARENT);
    password_textbox.Width(LENGTH_FILL_PARENT);
    password_textbox.Hint("Hint for Text_Box2");
    Vertical_Arrangement2 = new VerticalArrangement(HorizontalArrangement2);
    Vertical_Arrangement2.BackgroundColor(0x00FFFFFF);
    Vertical_Arrangement2.Height(LENGTH_FILL_PARENT);
    Vertical_Arrangement2.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement3 = new HorizontalArrangement(this);
    HorizontalArrangement3.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement3.Height(LENGTH_FILL_PARENT);
    HorizontalArrangement3.Width(LENGTH_FILL_PARENT);
    EULA_textbox = new CheckBox(HorizontalArrangement3);
    Eula = new Label(HorizontalArrangement3);
    Eula.Text("I agree with the EULA of the app.");
    HorizontalArrangement4 = new HorizontalArrangement(this);
    HorizontalArrangement4.AlignHorizontal(3);
    HorizontalArrangement4.AlignVertical(2);
    HorizontalArrangement4.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement4.Height(LENGTH_FILL_PARENT);
    HorizontalArrangement4.Width(LENGTH_FILL_PARENT);
    Login_button = new Button(HorizontalArrangement4);
    Login_button.BackgroundColor(0xFF009688);
    Login_button.FontSize(20);
    Login_button.Text("Login");
    Login_button.TextColor(0xFF000000);
    HorizontalArrangement5 = new HorizontalArrangement(this);
    HorizontalArrangement5.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement5.Height(LENGTH_FILL_PARENT);
    HorizontalArrangement5.Width(LENGTH_FILL_PARENT);
    WrongUserPassNotifier = new Notifier(this);
    Tiny_DB1 = new TinyDB(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}